import { VerticalBox, HorizontalBox, GridBox } from "std-widgets.slint";
import { Card, TabButton } from "components.slint";

export component InformationView inherits VerticalBox {
    in property <string> os-name;
    in property <string> kernel-version;
    in property <string> hostname;
    in property <string> uptime;
    in property <string> cpu-brand;
    in property <int> cpu-cores;
    in property <string> total-memory;
    in property <brush> text-color;
    in property <brush> card-bg;
    in property <brush> card-border;

    in property <string> bios-version;
    in property <string> storage-total;
    in property <string> gpu-names;

    property <int> active-tab: 0;

    padding: 20px;
    spacing: 20px;

    HorizontalBox {
        alignment: start;
        spacing: 10px;
        TabButton {
            text: "Software";
            active: root.active-tab == 0;
            text-color: root.text-color;
            clicked => {
                root.active-tab = 0;
            }
        }

        TabButton {
            text: "Hardware";
            active: root.active-tab == 1;
            text-color: root.text-color;
            clicked => {
                root.active-tab = 1;
            }
        }
    }

    if root.active-tab == 0: Card {
        card-title: "System Software";
        bg-color: root.card-bg;
        card-border-color: root.card-border;
        text-color: root.text-color;

        VerticalBox {
            spacing: 15px;
            HorizontalBox {
                Text {
                    text: "Hostname:";
                    width: 150px;
                    color: root.text-color;
                    font-weight: 700;
                }

                Text {
                    text: root.hostname;
                    color: root.text-color;
                }
            }

            HorizontalBox {
                Text {
                    text: "OS:";
                    width: 150px;
                    color: root.text-color;
                    font-weight: 700;
                }

                Text {
                    text: root.os-name;
                    color: root.text-color;
                }
            }

            HorizontalBox {
                Text {
                    text: "Kernel:";
                    width: 150px;
                    color: root.text-color;
                    font-weight: 700;
                }

                Text {
                    text: root.kernel-version;
                    color: root.text-color;
                }
            }

            HorizontalBox {
                Text {
                    text: "BIOS Mode/Ver:";
                    width: 150px;
                    color: root.text-color;
                    font-weight: 700;
                }

                Text {
                    text: root.bios-version;
                    color: root.text-color;
                }
            }

            HorizontalBox {
                Text {
                    text: "Uptime:";
                    width: 150px;
                    color: root.text-color;
                    font-weight: 700;
                }

                Text {
                    text: root.uptime;
                    color: root.text-color;
                }
            }
        }
    }

    if root.active-tab == 1: Card {
        card-title: "Hardware Specs";
        bg-color: root.card-bg;
        card-border-color: root.card-border;
        text-color: root.text-color;

        VerticalBox {
            spacing: 15px;

            HorizontalBox {
                Text {
                    text: "Processor:";
                    width: 150px;
                    color: root.text-color;
                    font-weight: 700;
                }

                Text {
                    text: root.cpu-brand;
                    color: root.text-color;
                    wrap: word-wrap;
                }
            }

            HorizontalBox {
                Text {
                    text: "Logical Cores:";
                    width: 150px;
                    color: root.text-color;
                    font-weight: 700;
                }

                Text {
                    text: root.cpu-cores;
                    color: root.text-color;
                }
            }

            HorizontalBox {
                Text {
                    text: "Total Memory:";
                    width: 150px;
                    color: root.text-color;
                    font-weight: 700;
                }

                Text {
                    text: root.total-memory;
                    color: root.text-color;
                }
            }

            HorizontalBox {
                Text {
                    text: "Total Storage:";
                    width: 150px;
                    color: root.text-color;
                    font-weight: 700;
                }

                Text {
                    text: root.storage-total;
                    color: root.text-color;
                }
            }

            if root.gpu-names != "": HorizontalBox {
                Text {
                    text: "GPU(s):";
                    width: 150px;
                    color: root.text-color;
                    font-weight: 700;
                }

                Text {
                    text: root.gpu-names;
                    color: root.text-color;
                    wrap: word-wrap;
                }
            }
        }
    }
    Rectangle {
        vertical-stretch: 1;
    }
}
